# Generated by Django 3.1.7 on 2021-05-15 05:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import service.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('res_image', models.ImageField(blank=True, null=True, upload_to='res_images/', validators=[service.validators.validate_size, service.validators.validate_extension])),
                ('res_phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+879999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('res_description', models.TextField(default='none')),
                ('city', models.CharField(default='Almaty', max_length=64, verbose_name='city')),
                ('country', models.CharField(default='Kazakhstan', max_length=64, verbose_name='country')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retaurants', to='auth_.profile')),
            ],
            options={
                'verbose_name_plural': "Restraunt's Infos",
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item_images/', validators=[service.validators.validate_size, service.validators.validate_extension])),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ManyToManyField(related_name='item', to='service.Category')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auth_.profile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service.restaurant')),
            ],
        ),
    ]
